require "stringio"
require "thread"
require "rake"
require "weave"

require "fezzik/base"
require "fezzik/colors"
require "fezzik/dsl"
require "fezzik/environment"
require "fezzik/role"
require "fezzik/io"
require "fezzik/util"
require "fezzik/version"
